# Tell travis we need copy fo docker running
# Build image using docker dev file
# tell travis to run test suite
# tell travis to deploy to AWS

sudo: required
services:
  - docker

before_install:
  - docker build -t abhinavprakash/docker-react -f Dockerfile.dev .